name: CD

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  download:
    runs-on: ubuntu-latest
    name: Run sh file and deploy
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install pandoc perl -y
      - name: Run file
        run: |
          chmod +x main.sh
          ./main.sh
      - uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - run: pip install \
          mkdocs-material \
          mkdocs-static-i18n
      - name: Deploy
        run: mkdocs gh-deploy --force